var lyricapp = {
    directory: "/Users/stevemansour/Documents/src/js/aegen/lyricvid",
    songTitle: "Living Life",
    introDuration: 5,           // seconds
    songDuration: 3*60 + 47,    // seconds
    lyricStart: 7,              // seconds
    lyricStop: 3*60 + 40,       // seconds
};
fontList = [
	"ACaslonPro-Bold",
	"ACaslonPro-BoldItalic",
	"ACaslonPro-Italic",
	"ACaslonPro-Regular",
	"ACaslonPro-Semibold",
	"ACaslonPro-SemiboldItalic",
	"AcuminConcept-Black",
	"AcuminConcept-BlackItalic",
	"AcuminConcept-Bold",
	"AcuminConcept-BoldItalic",
	"AcuminConcept-Condensed",
	"AcuminConcept-CondensedBlack",
	"AcuminConcept-CondensedBlackItalic",
	"AcuminConcept-CondensedBold",
	"AcuminConcept-CondensedBoldItalic",
	"AcuminConcept-CondensedExtraLight",
	"AcuminConcept-CondensedExtraLightItalic",
	"AcuminConcept-CondensedItalic",
	"AcuminConcept-CondensedLight",
	"AcuminConcept-CondensedLightItalic",
	"AcuminConcept-CondensedMedium",
	"AcuminConcept-CondensedMediumItalic",
	"AcuminConcept-CondensedSemibold",
	"AcuminConcept-CondensedSemiboldItalic",
	"AcuminConcept-CondensedThin",
	"AcuminConcept-CondensedThinItalic",
	"AcuminConcept-CondensedUltraBlack",
	"AcuminConcept-CondensedUltraBlackItalic",
	"AcuminConcept-ExtraCondensed",
	"AcuminConcept-ExtraCondensedBlack",
	"AcuminConcept-ExtraCondensedBlackItalic",
	"AcuminConcept-ExtraCondensedBold",
	"AcuminConcept-ExtraCondensedBoldItalic",
	"AcuminConcept-ExtraCondensedExtraLight",
	"AcuminConcept-ExtraCondensedExtraLightItalic",
	"AcuminConcept-ExtraCondensedItalic",
	"AcuminConcept-ExtraCondensedLight",
	"AcuminConcept-ExtraCondensedLightItalic",
	"AcuminConcept-ExtraCondensedMedium",
	"AcuminConcept-ExtraCondensedMediumItalic",
	"AcuminConcept-ExtraCondensedSemibold",
	"AcuminConcept-ExtraCondensedSemiboldItalic",
	"AcuminConcept-ExtraCondensedThin",
	"AcuminConcept-ExtraCondensedThinItalic",
	"AcuminConcept-ExtraCondensedUltraBlack",
	"AcuminConcept-ExtraCondensedUltraBlackItalic",
	"AcuminConcept-ExtraLight",
	"AcuminConcept-ExtraLightItalic",
	"AcuminConcept-Italic",
	"AcuminConcept-Light",
	"AcuminConcept-LightItalic",
	"AcuminConcept-Medium",
	"AcuminConcept-MediumItalic",
	"AcuminConcept-Regular",
	"AcuminConcept-Semibold",
	"AcuminConcept-SemiboldItalic",
	"AcuminConcept-SemiCondensed",
	"AcuminConcept-SemiCondensedBlack",
	"AcuminConcept-SemiCondensedBlackItalic",
	"AcuminConcept-SemiCondensedBold",
	"AcuminConcept-SemiCondensedBoldItalic",
	"AcuminConcept-SemiCondensedExtraLight",
	"AcuminConcept-SemiCondensedExtraLightItalic",
	"AcuminConcept-SemiCondensedItalic",
	"AcuminConcept-SemiCondensedLight",
	"AcuminConcept-SemiCondensedLightItalic",
	"AcuminConcept-SemiCondensedMedium",
	"AcuminConcept-SemiCondensedMediumItalic",
	"AcuminConcept-SemiCondensedSemibold",
	"AcuminConcept-SemiCondensedSemiboldItalic",
	"AcuminConcept-SemiCondensedThin",
	"AcuminConcept-SemiCondensedThinItalic",
	"AcuminConcept-SemiCondensedUltraBlack",
	"AcuminConcept-SemiCondensedUltraBlackItalic",
	"AcuminConcept-Thin",
	"AcuminConcept-ThinItalic",
	"AcuminConcept-UltraBlack",
	"AcuminConcept-UltraBlackItalic",
	"AcuminConcept-Wide",
	"AcuminConcept-WideBlack",
	"AcuminConcept-WideBlackItalic",
	"AcuminConcept-WideBold",
	"AcuminConcept-WideBoldItalic",
	"AcuminConcept-WideExtraLight",
	"AcuminConcept-WideExtraLightItalic",
	"AcuminConcept-WideItalic",
	"AcuminConcept-WideLight",
	"AcuminConcept-WideLightItalic",
	"AcuminConcept-WideMedium",
	"AcuminConcept-WideMediumItalic",
	"AcuminConcept-WideSemibold",
	"AcuminConcept-WideSemiboldItalic",
	"AcuminConcept-WideThin",
	"AcuminConcept-WideThinItalic",
	"AcuminConcept-WideUltraBlack",
	"AcuminConcept-WideUltraBlackItalic",
	"AcuminVariableConcept",
	"Adlibitum",
	"Adlibitum-Bold",
	"Adlibitum-Light",
	"AdobeArabic-Bold",
	"AdobeArabic-BoldItalic",
	"AdobeArabic-Italic",
	"AdobeArabic-Regular",
	"AdobeDevanagari-Bold",
	"AdobeDevanagari-BoldItalic",
	"AdobeDevanagari-Italic",
	"AdobeDevanagari-Regular",
	"AdobeFangsongStd-Regular",
	"AdobeFanHeitiStd-Bold",
	"AdobeGothicStd-Bold",
	"AdobeGurmukhi-Bold",
	"AdobeGurmukhi-Regular",
	"AdobeHebrew-Bold",
	"AdobeHebrew-BoldItalic",
	"AdobeHebrew-Italic",
	"AdobeHebrew-Regular",
	"AdobeHeitiStd-Regular",
	"AdobeKaitiStd-Regular",
	"AdobeMingStd-Light",
	"AdobeMyungjoStd-Medium",
	"AdobeNaskh-Medium",
	"AdobeSongStd-Light",
	"AeroMaticsBold",
	"AeroMaticsBoldItalic",
	"AeroMaticsDisplayBold",
	"AeroMaticsDisplayBoldItalic",
	"AeroMaticsDisplayItalic",
	"AeroMaticsDisplayLightItalic",
	"AeroMaticsDisplayLightRegular",
	"AeroMaticsDisplayRegular",
	"AeroMaticsItalic",
	"AeroMaticsLightItalic",
	"AeroMaticsLightRegular",
	"AeroMaticsRegular",
	"AGaramondPro-Bold",
	"AGaramondPro-BoldItalic",
	"AGaramondPro-Italic",
	"AGaramondPro-Regular",
	"AHDN",
	"AlBayan",
	"AlBayan-Bold",
	"AlNile",
	"AlNile-Bold",
	"AlTarikh",
	"AmericanTypewriter",
	"AmericanTypewriter-Bold",
	"AmericanTypewriter-Condensed",
	"AmericanTypewriter-CondensedBold",
	"AmericanTypewriter-CondensedLight",
	"AmericanTypewriter-Light",
	"AmericanTypewriter-Semibold",
	"AndaleMono",
	"Antonio-Bold",
	"Antonio-Regular",
	"Apple-Chancery",
	"AppleBraille",
	"AppleBraille-Outline6Dot",
	"AppleBraille-Outline8Dot",
	"AppleBraille-Pinpoint6Dot",
	"AppleBraille-Pinpoint8Dot",
	"AppleColorEmoji",
	"AppleGothic",
	"AppleMyungjo",
	"AppleSDGothicNeo-Bold",
	"AppleSDGothicNeo-ExtraBold",
	"AppleSDGothicNeo-Heavy",
	"AppleSDGothicNeo-Light",
	"AppleSDGothicNeo-Medium",
	"AppleSDGothicNeo-Regular",
	"AppleSDGothicNeo-SemiBold",
	"AppleSDGothicNeo-Thin",
	"AppleSDGothicNeo-UltraLight",
	"AppleSymbols",
	"ArchivoBlack-Regular",
	"Arial-Black",
	"Arial-BoldItalicMT",
	"Arial-BoldMT",
	"Arial-ItalicMT",
	"ArialHebrew",
	"ArialHebrew-Bold",
	"ArialHebrew-Light",
	"ArialHebrewScholar",
	"ArialHebrewScholar-Bold",
	"ArialHebrewScholar-Light",
	"ArialMT",
	"ArialNarrow",
	"ArialNarrow-Bold",
	"ArialNarrow-BoldItalic",
	"ArialNarrow-Italic",
	"ArialRoundedMTBold",
	"ArialUnicodeMS",
	"ArimaMadurai-Black",
	"ArimaMadurai-Regular",
	"Athelas-Bold",
	"Athelas-BoldItalic",
	"Athelas-Italic",
	"Athelas-Regular",
	"Avenir-Black",
	"Avenir-BlackOblique",
	"Avenir-Book",
	"Avenir-BookOblique",
	"Avenir-Heavy",
	"Avenir-HeavyOblique",
	"Avenir-Light",
	"Avenir-LightOblique",
	"Avenir-Medium",
	"Avenir-MediumOblique",
	"Avenir-Oblique",
	"Avenir-Roman",
	"AvenirNext-Bold",
	"AvenirNext-BoldItalic",
	"AvenirNext-DemiBold",
	"AvenirNext-DemiBoldItalic",
	"AvenirNext-Heavy",
	"AvenirNext-HeavyItalic",
	"AvenirNext-Italic",
	"AvenirNext-Medium",
	"AvenirNext-MediumItalic",
	"AvenirNext-Regular",
	"AvenirNext-UltraLight",
	"AvenirNext-UltraLightItalic",
	"AvenirNextCondensed-Bold",
	"AvenirNextCondensed-BoldItalic",
	"AvenirNextCondensed-DemiBold",
	"AvenirNextCondensed-DemiBoldItalic",
	"AvenirNextCondensed-Heavy",
	"AvenirNextCondensed-HeavyItalic",
	"AvenirNextCondensed-Italic",
	"AvenirNextCondensed-Medium",
	"AvenirNextCondensed-MediumItalic",
	"AvenirNextCondensed-Regular",
	"AvenirNextCondensed-UltraLight",
	"AvenirNextCondensed-UltraLightItalic",
	"Ayuthaya",
	"Baghdad",
	"Balford-Base",
	"BanditsOutline",
	"BanditsRegular",
	"BanditsShadow",
	"BanditsStriped",
	"BanglaMN",
	"BanglaMN-Bold",
	"BanglaSangamMN",
	"BanglaSangamMN-Bold",
	"BaseOne-Bold",
	"BaseOne-Heavy",
	"BaseOne-Regular",
	"Baskerville",
	"Baskerville-Bold",
	"Baskerville-BoldItalic",
	"Baskerville-Italic",
	"Baskerville-SemiBold",
	"Baskerville-SemiBoldItalic",
	"Baton-Decorative",
	"Beardsons-Normal",
	"BebasNeue-Regular",
	"BebasNeueBold",
	"Beirut",
	"BellBottom",
	"BenfordDEMO",
	"BigCaslon-Medium",
	"BigNoodleTitling",
	"BigNoodleTitling-Oblique",
	"BirchStd",
	"bitwise",
	"BlackBassDemo",
	"BlackHanSans-Regular",
	"BlackoakStd",
	"Blackriver-Bold",
	"BodoniOrnamentsITCTT",
	"BodoniSvtyTwoITCTT-Bold",
	"BodoniSvtyTwoITCTT-Book",
	"BodoniSvtyTwoITCTT-BookIta",
	"BodoniSvtyTwoOSITCTT-Bold",
	"BodoniSvtyTwoOSITCTT-Book",
	"BodoniSvtyTwoOSITCTT-BookIt",
	"BodoniSvtyTwoSCITCTT-Book",
	"BOOTLE",
	"BradleyHandITCTT-Bold",
	"Brilon-Regular",
	"BrushScriptMT",
	"BrushScriptStd",
	"CalisMTBol",
	"CastlePressNo2",
	"CastlePressNo2-border",
	"CasualHardcore",
	"CCUpUpAndAway",
	"Chalkboard",
	"Chalkboard-Bold",
	"ChalkboardSE-Bold",
	"ChalkboardSE-Light",
	"ChalkboardSE-Regular",
	"Chalkduster",
	"ChaparralPro-Bold",
	"ChaparralPro-BoldIt",
	"ChaparralPro-Italic",
	"ChaparralPro-LightIt",
	"ChaparralPro-Regular",
	"CharlemagneStd-Bold",
	"Charter-Black",
	"Charter-BlackItalic",
	"Charter-Bold",
	"Charter-BoldItalic",
	"Charter-Italic",
	"Charter-Roman",
	"Cochin",
	"Cochin-Bold",
	"Cochin-BoldItalic",
	"Cochin-Italic",
	"ComicSansMS",
	"ComicSansMS-Bold",
	"Copperplate",
	"Copperplate-Bold",
	"Copperplate-Light",
	"CorsivaHebrew",
	"CorsivaHebrew-Bold",
	"Courier",
	"Courier-Bold",
	"Courier-BoldOblique",
	"Courier-Oblique",
	"CourierNewPS-BoldItalicMT",
	"CourierNewPS-BoldMT",
	"CourierNewPS-ItalicMT",
	"CourierNewPSMT",
	"Coustard-Regular",
	"Cynzia-Bold",
	"Damascus",
	"DamascusBold",
	"DamascusLight",
	"DamascusMedium",
	"DamascusSemiBold",
	"DecoTypeNaskh",
	"den-Regular",
	"Descuadrado",
	"DescuadradoBold",
	"DescuadradoHollow",
	"DevanagariMT",
	"DevanagariMT-Bold",
	"DevanagariSangamMN",
	"DevanagariSangamMN-Bold",
	"Didot",
	"Didot-Bold",
	"Didot-Italic",
	"DINAlternate-Bold",
	"DINCondensed-Bold",
	"DiwanKufi",
	"DiwanMishafi",
	"DiwanMishafiGold",
	"DiwanThuluth",
	"DPSDbeyond",
	"Eldebaran",
	"Eldebaran3D",
	"Eldebaran3DItalic",
	"EldebaranAcademy",
	"EldebaranAcademyItalic",
	"EldebaranBold",
	"EldebaranBoldItalic",
	"EldebaranCondensed",
	"EldebaranCondensedItalic",
	"EldebaranExpanded",
	"EldebaranExpandedItalic",
	"EldebaranItalic",
	"EldebaranLaser",
	"EldebaranLaserItalic",
	"EldebaranLeftalic",
	"EldebaranOutline",
	"EldebaranOutlineItalic",
	"EmojiOneColor",
	"EricaType-Bold",
	"EricaType-BoldItalic",
	"EricaType-Italic",
	"EricaType-Regular",
	"EuphemiaUCAS",
	"EuphemiaUCAS-Bold",
	"EuphemiaUCAS-Italic",
	"Farah",
	"Farisi",
	"Flames",
	"Folklore",
	"ForgottenFuturist",
	"ForgottenFuturist-Bold",
	"ForgottenFuturist-BoldItalic",
	"ForgottenFuturist-Italic",
	"ForgottenFuturistShadow",
	"Futura-Bold",
	"Futura-CondensedExtraBold",
	"Futura-CondensedMedium",
	"Futura-Medium",
	"Futura-MediumItalic",
	"Gallagher-Stamp",
	"GB18030Bitmap",
	"GeezaPro",
	"GeezaPro-Bold",
	"Geneva",
	"Georgia",
	"Georgia-Bold",
	"Georgia-BoldItalic",
	"Georgia-Italic",
	"GillSans",
	"GillSans-Bold",
	"GillSans-BoldItalic",
	"GillSans-Italic",
	"GillSans-Light",
	"GillSans-LightItalic",
	"GillSans-SemiBold",
	"GillSans-SemiBoldItalic",
	"GillSans-UltraBold",
	"Gizmo",
	"Gizmo-Bold",
	"Gizmo-Shade",
	"Gretoon",
	"GretoonHighlight",
	"GujaratiMT",
	"GujaratiMT-Bold",
	"GujaratiSangamMN",
	"GujaratiSangamMN-Bold",
	"GurmukhiMN",
	"GurmukhiMN-Bold",
	"GurmukhiSangamMN",
	"GurmukhiSangamMN-Bold",
	"Heathergreen",
	"Helvetica",
	"Helvetica-Bold",
	"Helvetica-BoldOblique",
	"Helvetica-Light",
	"Helvetica-LightOblique",
	"Helvetica-Oblique",
	"HelveticaNeue",
	"HelveticaNeue-Bold",
	"HelveticaNeue-BoldItalic",
	"HelveticaNeue-CondensedBlack",
	"HelveticaNeue-CondensedBold",
	"HelveticaNeue-Italic",
	"HelveticaNeue-Light",
	"HelveticaNeue-LightItalic",
	"HelveticaNeue-Medium",
	"HelveticaNeue-MediumItalic",
	"HelveticaNeue-Thin",
	"HelveticaNeue-ThinItalic",
	"HelveticaNeue-UltraLight",
	"HelveticaNeue-UltraLightItalic",
	"Hennigar",
	"Herculanum",
	"HFFEyeSore",
	"HighlandGothicFLF",
	"HighlandGothicFLF-Bold",
	"HighlandGothicLightFLF",
	"HillwayRegular",
	"HipPocket",
	"HipPocket3D",
	"HipPocket3DItalic",
	"HipPocketAcademy",
	"HipPocketAcademyItalic",
	"HipPocketCondensed",
	"HipPocketCondensedItalic",
	"HipPocketExpanded",
	"HipPocketExpandedItalic",
	"HipPocketItalic",
	"HipPocketLeftalic",
	"HipPocketOutline",
	"HipPocketOutlineItalic",
	"HipPocketRotalic",
	"HiraginoSans-W0",
	"HiraginoSans-W1",
	"HiraginoSans-W2",
	"HiraginoSans-W3",
	"HiraginoSans-W4",
	"HiraginoSans-W5",
	"HiraginoSans-W6",
	"HiraginoSans-W7",
	"HiraginoSans-W8",
	"HiraginoSans-W9",
	"HiraginoSansGB-W3",
	"HiraginoSansGB-W6",
	"HiraKakuPro-W3",
	"HiraKakuPro-W6",
	"HiraKakuProN-W3",
	"HiraKakuProN-W6",
	"HiraKakuStd-W8",
	"HiraKakuStdN-W8",
	"HiraMaruPro-W4",
	"HiraMaruProN-W4",
	"HiraMinPro-W3",
	"HiraMinPro-W6",
	"HiraMinProN-W3",
	"HiraMinProN-W6",
	"HoboStd",
	"HoeflerText-Black",
	"HoeflerText-BlackItalic",
	"HoeflerText-Italic",
	"HoeflerText-Ornaments",
	"HoeflerText-Regular",
	"ImnovaSt",
	"Impact",
	"In-his-right-place",
	"InaiMathi",
	"InaiMathi-Bold",
	"IowanOldStyle-Black",
	"IowanOldStyle-BlackItalic",
	"IowanOldStyle-Bold",
	"IowanOldStyle-BoldItalic",
	"IowanOldStyle-Italic",
	"IowanOldStyle-Roman",
	"IowanOldStyle-Titling",
	"ITFDevanagari-Bold",
	"ITFDevanagari-Book",
	"ITFDevanagari-Demi",
	"ITFDevanagari-Light",
	"ITFDevanagari-Medium",
	"ITFDevanagariMarathi-Bold",
	"ITFDevanagariMarathi-Book",
	"ITFDevanagariMarathi-Demi",
	"ITFDevanagariMarathi-Light",
	"ITFDevanagariMarathi-Medium",
	"Justify",
	"Kailasa",
	"Kailasa-Bold",
	"KannadaMN",
	"KannadaMN-Bold",
	"KannadaSangamMN",
	"KannadaSangamMN-Bold",
	"KeeponTruckin",
	"Kefa-Bold",
	"Kefa-Regular",
	"KhmerMN",
	"KhmerMN-Bold",
	"KhmerSangamMN",
	"KohinoorBangla-Bold",
	"KohinoorBangla-Light",
	"KohinoorBangla-Medium",
	"KohinoorBangla-Regular",
	"KohinoorBangla-Semibold",
	"KohinoorDevanagari-Bold",
	"KohinoorDevanagari-Light",
	"KohinoorDevanagari-Medium",
	"KohinoorDevanagari-Regular",
	"KohinoorDevanagari-Semibold",
	"KohinoorTelugu-Bold",
	"KohinoorTelugu-Light",
	"KohinoorTelugu-Medium",
	"KohinoorTelugu-Regular",
	"KohinoorTelugu-Semibold",
	"Kokonor",
	"KozGoPr6N-Bold",
	"KozGoPr6N-ExtraLight",
	"KozGoPr6N-Heavy",
	"KozGoPr6N-Light",
	"KozGoPr6N-Medium",
	"KozGoPr6N-Regular",
	"KozGoPro-Bold",
	"KozGoPro-ExtraLight",
	"KozGoPro-Heavy",
	"KozGoPro-Light",
	"KozGoPro-Medium",
	"KozGoPro-Regular",
	"KozMinPr6N-Bold",
	"KozMinPr6N-ExtraLight",
	"KozMinPr6N-Heavy",
	"KozMinPr6N-Light",
	"KozMinPr6N-Medium",
	"KozMinPr6N-Regular",
	"KozMinPro-Bold",
	"KozMinPro-ExtraLight",
	"KozMinPro-Heavy",
	"KozMinPro-Light",
	"KozMinPro-Medium",
	"KozMinPro-Regular",
	"Krungthep",
	"KufiStandardGK",
	"LaoMN",
	"LaoMN-Bold",
	"LaoSangamMN",
	"LetterGothicStd",
	"LetterGothicStd-Bold",
	"LetterGothicStd-BoldSlanted",
	"LetterGothicStd-Slanted",
	"LithosPro-Black",
	"LithosPro-Regular",
	"Lora-Bold",
	"Lora-Regular",
	"lowx-line",
	"LucidaGrande",
	"LucidaGrande-Bold",
	"Luminari-Regular",
	"MalayalamMN",
	"MalayalamMN-Bold",
	"MalayalamSangamMN",
	"MalayalamSangamMN-Bold",
	"Marion-Bold",
	"Marion-Italic",
	"Marion-Regular",
	"MarkerFelt-Thin",
	"MarkerFelt-Wide",
	"Menlo-Bold",
	"Menlo-BoldItalic",
	"Menlo-Italic",
	"Menlo-Regular",
	"MicrosoftSansSerif",
	"MiddleAgesPERSONALUSE",
	"minim",
	"MinionConceptItalic-BoldItalic",
	"MinionConceptItalic-DisplayBoldItalic",
	"MinionConceptItalic-DisplayItalic",
	"MinionConceptItalic-DisplayMediumItalic",
	"MinionConceptItalic-DisplaySemiboldItalic",
	"MinionConceptItalic-MediumItalic",
	"MinionConceptItalic-SemiboldItalic",
	"MinionConceptRoman-Bold",
	"MinionConceptRoman-Display",
	"MinionConceptRoman-DisplayBold",
	"MinionConceptRoman-DisplayMedium",
	"MinionConceptRoman-DisplaySemibold",
	"MinionConceptRoman-Medium",
	"MinionConceptRoman-Semibold",
	"MinionPro-Bold",
	"MinionPro-BoldCn",
	"MinionPro-BoldCnIt",
	"MinionPro-BoldIt",
	"MinionPro-It",
	"MinionPro-Medium",
	"MinionPro-MediumIt",
	"MinionPro-Regular",
	"MinionPro-Semibold",
	"MinionPro-SemiboldIt",
	"MinionVariableConcept-Italic",
	"MinionVariableConcept-Roman",
	"Mirosa-Regular",
	"MirosaSwash-Regular",
	"MNML",
	"Molot",
	"Monaco",
	"MonotypeGurmukhi",
	"Montheim",
	"Moon-Bold",
	"Moon-Light",
	"Mouser",
	"Mouser_Italic",
	"MouserOutline",
	"Mshtakan",
	"MshtakanBold",
	"MshtakanBoldOblique",
	"MshtakanOblique",
	"Muna",
	"MunaBlack",
	"MunaBold",
	"MyanmarMN",
	"MyanmarMN-Bold",
	"MyanmarSangamMN",
	"MyanmarSangamMN-Bold",
	"Myriad-Roman",
	"MyriadArabic-Bold",
	"MyriadArabic-BoldIt",
	"MyriadArabic-It",
	"MyriadArabic-Regular",
	"MyriadConceptItalic-BlackCondensedItalic",
	"MyriadConceptItalic-BlackItalic",
	"MyriadConceptItalic-BlackSemiCondensedItalic",
	"MyriadConceptItalic-BlackSemiExtendedItalic",
	"MyriadConceptItalic-BoldCondensedItalic",
	"MyriadConceptItalic-BoldItalic",
	"MyriadConceptItalic-BoldSemiCondensedItalic",
	"MyriadConceptItalic-BoldSemiExtendedItalic",
	"MyriadConceptItalic-CondensedItalic",
	"MyriadConceptItalic-Italic",
	"MyriadConceptItalic-LightItalic",
	"MyriadConceptItalic-LightSemiCondensedItalic",
	"MyriadConceptItalic-LightSemiExtendedItalic",
	"MyriadConceptItalic-SemiboldCondensedItalic",
	"MyriadConceptItalic-SemiboldItalic",
	"MyriadConceptItalic-SemiboldSemiCondensedItalic",
	"MyriadConceptItalic-SemiboldSemiExtendedItalic",
	"MyriadConceptItalic-SemiCondensedItalic",
	"MyriadConceptItalic-SemiExtendedItalic",
	"MyriadConceptRoman-Black",
	"MyriadConceptRoman-BlackCondensed",
	"MyriadConceptRoman-BlackSemiCondensed",
	"MyriadConceptRoman-BlackSemiExtended",
	"MyriadConceptRoman-Bold",
	"MyriadConceptRoman-BoldCondensed",
	"MyriadConceptRoman-BoldSemiCondensed",
	"MyriadConceptRoman-BoldSemiExtended",
	"MyriadConceptRoman-Condensed",
	"MyriadConceptRoman-Light",
	"MyriadConceptRoman-LightSemiCondensed",
	"MyriadConceptRoman-LightSemiExtended",
	"MyriadConceptRoman-Regular",
	"MyriadConceptRoman-Semibold",
	"MyriadConceptRoman-SemiboldCondensed",
	"MyriadConceptRoman-SemiboldSemiCondensed",
	"MyriadConceptRoman-SemiboldSemiExtended",
	"MyriadConceptRoman-SemiCondensed",
	"MyriadConceptRoman-SemiExtended",
	"MyriadHebrew-Bold",
	"MyriadHebrew-BoldIt",
	"MyriadHebrew-It",
	"MyriadHebrew-Regular",
	"MyriadPro-Bold",
	"MyriadPro-BoldCond",
	"MyriadPro-BoldCondIt",
	"MyriadPro-BoldIt",
	"MyriadPro-Cond",
	"MyriadPro-CondIt",
	"MyriadPro-It",
	"MyriadPro-Regular",
	"MyriadPro-Semibold",
	"MyriadPro-SemiboldIt",
	"MyriadVariableConcept-Italic",
	"MyriadVariableConcept-Roman",
	"Nadeem",
	"NewPeninimMT",
	"NewPeninimMT-Bold",
	"NewPeninimMT-BoldInclined",
	"NewPeninimMT-Inclined",
	"NiagaraSolid-Reg",
	"Not-Sure-If-Weird-Or-Just-Regular",
	"Noteworthy-Bold",
	"Noteworthy-Light",
	"NotoNastaliqUrdu",
	"NotoSansCham-Regular",
	"NSChamptoneScript",
	"NuevaStd-Bold",
	"NuevaStd-BoldCond",
	"NuevaStd-Cond",
	"NuevaStd-Italic",
	"NuevoPassion",
	"NuevoPassion3D",
	"NuevoPassion3DItalic",
	"NuevoPassionAcademy",
	"NuevoPassionAcademyItalic",
	"NuevoPassionCondensed",
	"NuevoPassionCondensedItalic",
	"NuevoPassionExpanded",
	"NuevoPassionExpandedItalic",
	"NuevoPassionItalic",
	"NuevoPassionLeftalic",
	"NuevoPassionRotalic",
	"NuevoPassionRotated",
	"OCRAStd",
	"OldAlfie-Regular",
	"OldErika-Regular",
	"Optima-Bold",
	"Optima-BoldItalic",
	"Optima-ExtraBlack",
	"Optima-Italic",
	"Optima-Regular",
	"OratorStd",
	"OriginalSurfer-Regular",
	"OriyaMN",
	"OriyaMN-Bold",
	"OriyaSangamMN",
	"OriyaSangamMN-Bold",
	"OxenCrossbow",
	"Palatino-Bold",
	"Palatino-BoldItalic",
	"Palatino-Italic",
	"Palatino-Roman",
	"Papyrus",
	"Papyrus-Condensed",
	"Peace&Houston",
	"Peace&Houston",
	"Peace&Houston3D",
	"Peace&Houston3D",
	"Peace&Houston3DItalic",
	"Peace&Houston3DItalic",
	"Peace&HoustonAcademy",
	"Peace&HoustonAcademy",
	"Peace&HoustonAcademyItalic",
	"Peace&HoustonAcademyItalic",
	"Peace&HoustonBold",
	"Peace&HoustonBold",
	"Peace&HoustonBoldItalic",
	"Peace&HoustonBoldItalic",
	"Peace&HoustonCondensed",
	"Peace&HoustonCondensed",
	"Peace&HoustonCondensedItal",
	"Peace&HoustonCondensedItal",
	"Peace&HoustonExpanded",
	"Peace&HoustonExpanded",
	"Peace&HoustonExpandedItal",
	"Peace&HoustonExpandedItal",
	"Peace&HoustonExtraBold",
	"Peace&HoustonExtraBold",
	"Peace&HoustonExtraBoldIta",
	"Peace&HoustonExtraBoldIta",
	"Peace&HoustonHalftone",
	"Peace&HoustonHalftone",
	"Peace&HoustonHalftoneItal",
	"Peace&HoustonHalftoneItal",
	"Peace&HoustonItalic",
	"Peace&HoustonItalic",
	"Peace&HoustonLaser",
	"Peace&HoustonLaser",
	"Peace&HoustonLaserItalic",
	"Peace&HoustonLaserItalic",
	"Peace&HoustonLeftalic",
	"Peace&HoustonLeftalic",
	"Peace&HoustonOutline",
	"Peace&HoustonOutline",
	"Peace&HoustonOutlineItalic",
	"Peace&HoustonOutlineItalic",
	"Peace&HoustonSemi-Bold",
	"Peace&HoustonSemi-Bold",
	"Peace&HoustonSemi-BoldItal",
	"Peace&HoustonSemi-BoldItal",
	"Peace&HoustonSemi-Italic",
	"Peace&HoustonSemi-Italic",
	"Peace&HoustonSuper-Italic",
	"Peace&HoustonSuper-Italic",
	"Peace&HoustonTitle",
	"Peace&HoustonTitle",
	"Peace&HoustonTitleItalic",
	"Peace&HoustonTitleItalic",
	"Peace&HoustonWide",
	"Peace&HoustonWide",
	"Peace&HoustonWideItalic",
	"Peace&HoustonWideItalic",
	"PeaceSans",
	"PhattPhreddyNF",
	"Phosphate-Inline",
	"Phosphate-Solid",
	"PingFangHK-Light",
	"PingFangHK-Medium",
	"PingFangHK-Regular",
	"PingFangHK-Semibold",
	"PingFangHK-Thin",
	"PingFangHK-Ultralight",
	"PingFangSC-Light",
	"PingFangSC-Medium",
	"PingFangSC-Regular",
	"PingFangSC-Semibold",
	"PingFangSC-Thin",
	"PingFangSC-Ultralight",
	"PingFangTC-Light",
	"PingFangTC-Medium",
	"PingFangTC-Regular",
	"PingFangTC-Semibold",
	"PingFangTC-Thin",
	"PingFangTC-Ultralight",
	"PlantagenetCherokee",
	"Plasmatic-Regular",
	"PoplarStd",
	"PrestigeEliteStd-Bd",
	"Preview",
	"Prototype",
	"PTMono-Bold",
	"PTMono-Regular",
	"PTSans-Bold",
	"PTSans-BoldItalic",
	"PTSans-Caption",
	"PTSans-CaptionBold",
	"PTSans-Italic",
	"PTSans-Narrow",
	"PTSans-NarrowBold",
	"PTSans-Regular",
	"PTSerif-Bold",
	"PTSerif-BoldItalic",
	"PTSerif-Caption",
	"PTSerif-CaptionItalic",
	"PTSerif-Italic",
	"PTSerif-Regular",
	"Pumpkin",
	"PuntiyiscaSt",
	"Raanana",
	"RaananaBold",
	"RacingFlow",
	"RemoveDEMO-Bold",
	"Rockwell-Bold",
	"Rockwell-BoldItalic",
	"Rockwell-Italic",
	"Rockwell-Regular",
	"RollKingDemoRegular",
	"RollKingDemoShadow",
	"RoyalSignage-Rg",
	"RubikMonoOne-Regular",
	"RumbleBrave",
	"Sana",
	"SANSON",
	"Sathu",
	"SavoyeLetPlain",
	"SelfDestructButtonBB",
	"SelfDestructButtonBB-Bold",
	"SelfDestructButtonBB-Italic",
	"Seravek",
	"Seravek-Bold",
	"Seravek-BoldItalic",
	"Seravek-ExtraLight",
	"Seravek-ExtraLightItalic",
	"Seravek-Italic",
	"Seravek-Light",
	"Seravek-LightItalic",
	"Seravek-Medium",
	"Seravek-MediumItalic",
	"Serpentine-Bold",
	"SFPiezolectric",
	"SFPiezolectric-Oblique",
	"SFPiezolectricCondensed",
	"SFPiezolectricCondensed-Oblique",
	"SFPiezolectricInline",
	"SFPiezolectricInline-Oblique",
	"SFPiezolectricSFX",
	"SFPiezolectricSFX-Oblique",
	"ShareTechMono-Regular",
	"ShreeDev0714",
	"ShreeDev0714-Bold",
	"ShreeDev0714-BoldItalic",
	"ShreeDev0714-Italic",
	"SignPainter-HouseScript",
	"SignPainter-HouseScriptSemibold",
	"Silom",
	"SinhalaMN",
	"SinhalaMN-Bold",
	"SinhalaSangamMN",
	"SinhalaSangamMN-Bold",
	"Skia-Black",
	"Skia-BlackCondensed",
	"Skia-BlackExtended",
	"Skia-Bold",
	"Skia-Condensed",
	"Skia-Extended",
	"Skia-Light",
	"Skia-LightCondensed",
	"Skia-LightExtended",
	"Skia-Regular",
	"Slimlines",
	"SnellRoundhand",
	"SnellRoundhand-Black",
	"SnellRoundhand-Bold",
	"SoftwareTester7",
	"SourceCodeItalic-BlackItalic",
	"SourceCodeItalic-BoldItalic",
	"SourceCodeItalic-ExtraLightItalic",
	"SourceCodeItalic-LightItalic",
	"SourceCodeItalic-MediumItalic",
	"SourceCodeItalic-SemiboldItalic",
	"SourceCodePro-Black",
	"SourceCodePro-Bold",
	"SourceCodePro-ExtraLight",
	"SourceCodePro-Light",
	"SourceCodePro-Regular",
	"SourceCodePro-Semibold",
	"SourceCodeRoman-Black",
	"SourceCodeRoman-Bold",
	"SourceCodeRoman-ExtraLight",
	"SourceCodeRoman-Light",
	"SourceCodeRoman-Medium",
	"SourceCodeRoman-Semibold",
	"SourceCodeVariable-Italic",
	"SourceCodeVariable-Roman",
	"SourceSansItalic-BlackItalic",
	"SourceSansItalic-BoldItalic",
	"SourceSansItalic-Italic",
	"SourceSansItalic-LightItalic",
	"SourceSansItalic-SemiboldItalic",
	"SourceSansPro-Black",
	"SourceSansPro-BlackIt",
	"SourceSansPro-Bold",
	"SourceSansPro-BoldIt",
	"SourceSansPro-ExtraLight",
	"SourceSansPro-ExtraLightIt",
	"SourceSansPro-It",
	"SourceSansPro-Light",
	"SourceSansPro-LightIt",
	"SourceSansPro-Regular",
	"SourceSansPro-Semibold",
	"SourceSansPro-SemiboldIt",
	"SourceSansRoman-Black",
	"SourceSansRoman-Bold",
	"SourceSansRoman-Light",
	"SourceSansRoman-Regular",
	"SourceSansRoman-Semibold",
	"SourceSansVariable-Italic",
	"SourceSansVariable-Roman",
	"SourceSerifRoman-Black",
	"SourceSerifRoman-Bold",
	"SourceSerifRoman-ExtraLight",
	"SourceSerifRoman-Light",
	"SourceSerifRoman-Regular",
	"SourceSerifRoman-Semibold",
	"SourceSerifVariable-Roman",
	"Steelfish",
	"Steelfish-Bold",
	"SteelfishOutline",
	"STHeitiSC-Light",
	"STHeitiSC-Medium",
	"STHeitiTC-Light",
	"STHeitiTC-Medium",
	"STIXGeneral-Bold",
	"STIXGeneral-BoldItalic",
	"STIXGeneral-Italic",
	"STIXGeneral-Regular",
	"STIXIntegralsD-Bold",
	"STIXIntegralsD-Regular",
	"STIXIntegralsSm-Bold",
	"STIXIntegralsSm-Regular",
	"STIXIntegralsUp-Bold",
	"STIXIntegralsUp-Regular",
	"STIXIntegralsUpD-Bold",
	"STIXIntegralsUpD-Regular",
	"STIXIntegralsUpSm-Bold",
	"STIXIntegralsUpSm-Regular",
	"STIXNonUnicode-Bold",
	"STIXNonUnicode-BoldItalic",
	"STIXNonUnicode-Italic",
	"STIXNonUnicode-Regular",
	"STIXSizeFiveSym-Regular",
	"STIXSizeFourSym-Bold",
	"STIXSizeFourSym-Regular",
	"STIXSizeOneSym-Bold",
	"STIXSizeOneSym-Regular",
	"STIXSizeThreeSym-Bold",
	"STIXSizeThreeSym-Regular",
	"STIXSizeTwoSym-Bold",
	"STIXSizeTwoSym-Regular",
	"STIXVariants-Bold",
	"STIXVariants-Regular",
	"StoneSansSemITCTTSemi",
	"STSong",
	"STSongti-SC-Black",
	"STSongti-SC-Bold",
	"STSongti-SC-Light",
	"STSongti-SC-Regular",
	"STSongti-TC-Bold",
	"STSongti-TC-Light",
	"STSongti-TC-Regular",
	"SukhumvitSet-Bold",
	"SukhumvitSet-Light",
	"SukhumvitSet-Medium",
	"SukhumvitSet-SemiBold",
	"SukhumvitSet-Text",
	"SukhumvitSet-Thin",
	"Superclarendon-Black",
	"Superclarendon-BlackItalic",
	"Superclarendon-Bold",
	"Superclarendon-BoldItalic",
	"Superclarendon-Italic",
	"Superclarendon-Light",
	"Superclarendon-LightItalic",
	"Superclarendon-Regular",
	"SuperRetroM54",
	"SuperRetroM54-Italic",
	"Symbol",
	"Tahoma",
	"Tahoma-Bold",
	"TamilMN",
	"TamilMN-Bold",
	"TamilSangamMN",
	"TamilSangamMN-Bold",
	"TeamViewer10",
	"Teatral",
	"TektonPro-Bold",
	"TektonPro-BoldCond",
	"TektonPro-BoldExt",
	"TektonPro-BoldObl",
	"TeluguMN",
	"TeluguMN-Bold",
	"TeluguSangamMN",
	"TeluguSangamMN-Bold",
	"TH3-MACHINE",
	"TheLostCanyon",
	"TheLostCanyon-Italic",
	"Thonburi",
	"Thonburi-Bold",
	"Thonburi-Light",
	"Times-Bold",
	"Times-BoldItalic",
	"Times-Italic",
	"Times-Roman",
	"TimesNewRomanPS-BoldItalicMT",
	"TimesNewRomanPS-BoldMT",
	"TimesNewRomanPS-ItalicMT",
	"TimesNewRomanPSMT",
	"TopComicPersonalUseOnly",
	"TrajanColor-Concept",
	"TrajanPro3-Bold",
	"TrajanPro3-Regular",
	"Trattatello",
	"Trebuchet-BoldItalic",
	"TrebuchetMS",
	"TrebuchetMS-Bold",
	"TrebuchetMS-Italic",
	"TwoFiftySixBytes-Regular",
	"TYPOGRAPHPRO-ExtraBold",
	"TYPOGRAPHPRO-Light",
	"TYPOGRAPHPRO-LightItalic",
	"TYPOGRAPHPRO-SemiBold",
	"TYPOGRAPHPRO-SemiBoldItalic",
	"TYPOGRAPHPRO-UltraLight",
	"TYPOGRAPHPRO-UltraLightItalic",
	"TypolineExpanded",
	"TypolineExpanded-Italic",
	"UnionGray",
	"UnionGray3D",
	"UnionGray3DItalic",
	"UnionGray3DSemi-Italic",
	"UnionGrayCondensed",
	"UnionGrayCondensedItalic",
	"UnionGrayCondensedSemi-Italic",
	"UnionGrayExpanded",
	"UnionGrayExpandedItalic",
	"UnionGrayExpandedSemi-Italic",
	"UnionGrayHalftone",
	"UnionGrayHalftoneItalic",
	"UnionGrayHalftoneSemi-Italic",
	"UnionGrayItalic",
	"UnionGrayLeftalic",
	"UnionGrayOutline",
	"UnionGrayOutlineItalic",
	"UnionGrayOutlineSemi-Italic",
	"UnionGraySemi-Italic",
	"UnionGraySuper-Italic",
	"Verdana",
	"Verdana-Bold",
	"Verdana-BoldItalic",
	"Verdana-Italic",
	"Waseem",
	"WaseemLight",
	"Webdings",
	"WickedMouse",
	"windi",
	"Wingdings-Regular",
	"Wingdings2",
	"Wingdings3",
	"Wonderland-Medium",
	"ZapfDingbatsITC",
	"Zapfino",
	"ZenzaiItacha",
	"ZenzaiItache",
	"ZenzaiItachi",
];
// After Effects script
//=============================================================================

function createSong() {
    var song = {
        lyrics: [
            "and I'm thinking",
            "'bout this caged-in life",
            "can't help feeling",
            "life has passed me by",
            "I just don't understand",
            "the point of it all sometimes",
            "or the mouse in the trap",
            "that struggles before it dies",
            "so I'm calling",
            "up my boys tonight",
            "night is falling",
            "so just one more time",
            "I said Hey",
            "gonna play tonight",
            "Have a round, drink it down",
            "and the next one's mine",
            "Let's go out with a blast",
            "and let's do it right",
            "One more time",
            "Livin' Life",
            "Too much drinking",
            "I hear nature's call",
            "counting cracks in",
            "this grimy bathroom wall",
            "seeing double",
            "don't think I should drive",
            "I should stop now",
            "while I can still count to five",
            "But it's Hey, Hey, Hey",
            "life's okay tonight",
            "While we're here commandeer",
            "all the hootch in sight",
            "Let's go out with a blast",
            "and let's do it right",
            "One more time",
            "Livin' Life",
            "We're not as young as we used to be",
            "but we're taking this chance",
            "We're gonna make us some history",
            "while there's still time to dance",
            "d d d d d d dance!",
            "I said Hey, Hey, Hey",
            "and we play tonight",
            "Coke and Crown, all around",
            "but the bottom line",
            "Is we're out with a blast",
            "so let's do it right",
            "One more time",
            "Livin' Life",
            "I said Hey tonight",
            "Singing cheers while we're here",
            "for just one more time",
            "Let's go out with a blast",
            "and let's do it right",
            "One more time",
            "Livin' Life",
        ],
        solos: [
            { start: 0*60 + 55, stop: 1*60 +  4 },
            // { start: 1*60 + 21, stop: 1*60 + 28 },
            // { start: 2*60 + 19, stop: 2*60 + 22 },
            // { start: 2*60 + 38, stop: 2*60 + 40 },
            { start: 2*60 + 45, stop: 3*60 +  6 },
        ],
};
    return song;
}

function setupTextDocument(tdoc) {
    tdoc.resetCharStyle();
    tdoc.resetParagraphStyle();
    tdoc.font = "Calibri";
    tdoc.fontSize = 100;
    tdoc.fillColor = [1,1,1];
    tdoc.strokeColor = [0,1,0];
    tdoc.strokeWidth = 2;
    tdoc.strokeOverFill = true;
    tdoc.applyStroke = false;
    tdoc.applyFill = true;
    tdoc.justification = ParagraphJustification.CENTER_JUSTIFY;
    tdoc.tracking = 50;
    tdoc.leading = 25;
    return tdoc;
}

// INPUT
//   n = index of the solo
//
// RETURNS
//   the video time for where this solo begins...
//-----------------------------------------------------------------------------
function soloStartTime(song,n) {
    return lyricapp.introDuration + song.solos[n].start;
}

// INPUT
//   n = index of the solo
//
// RETURNS
//   the video time for where this solo ends...
//-----------------------------------------------------------------------------
function soloStopTime(song,n) {
    return lyricapp.introDuration + song.solos[n].stop;
}

function buildLyricVid() {
    // var comp = lyricapp.comp;
    var song = createSong();   // load lyrics, set times where lyrics are excluded
    var i;

    //-----------------------------------------------------------------------
    // Step 1.  When does first vocal start, when does the last vocal stop.
    //          This forms the initial lyric time.
    //-----------------------------------------------------------------------
    var lyricDuration = lyricapp.lyricStop - lyricapp.lyricStart;

    //-----------------------------------------------------------------------
    // Next, how much time is taken is taken up by solos...
    // The idea is to space the lines out evenly and dodge the solo areas
    //-----------------------------------------------------------------------
    var solotime = 0;
    var soloidx = -1;  // assume no solos
    var solostart = 0; // assume no solo
    if (song.solos.length > 0) {
        soloidx = 0;   // if there are solos, this is the first one
        soloStart = soloStartTime(song,soloidx);
    }
    for (i = 0; i < song.solos.length; i++) {
        lyricDuration -= song.solos[i].stop - song.solos[i].start;  // duration of this solo
    }

    var inTime = lyricapp.lyricStart;  // First lyric line goes here
    var layer, tprop, tdoc;

    var proj = app.project;
    if(!proj) {
        proj = app.newProject();
    }

    // create new comp
    var compW = 1920;                   // comp width
    var compH = 1080;                   // comp height
    var compL = lyricapp.songDuration;      // comp length (seconds)
    var compRate = 30;                  // comp frame rate
    var compBG = [48/255,63/255,84/255] // comp background color

    var myItemCollection = app.project.items;
    var comp = myItemCollection.addComp('LyricVideo',compW,compH,1,compL,compRate);
    comp.bgColor = compBG;

    //-----------------------------------------------------------------------
    // Compute how long is each lyric is visible.  This is approximated as the
    // total time lyrics are sung divided by the number of lines of lyrics.
    // This is certainly not perfect, but it's a reasonable starting point.
    //-----------------------------------------------------------------------
    var dt = lyricDuration / song.lyrics.length;

    //-----------------------------------------------------------------------
    // Now spin through each line of the song and add it
    //-----------------------------------------------------------------------
    for (i = 0; i < song.lyrics.length; i++) {
        layer = comp.layers.addText(song.lyrics[i]);
        tprop = layer.property("Source Text");
        tdoc = setupTextDocument(tprop.value);
        tprop.setValue(tdoc);
        layer.inPoint = inTime;
        inTime += dt;
        layer.outPoint = inTime;

        //------------------------------------------------------------------
        // Quck check to see if we've moved into any of the solo spaces.
        // if so, jump around it.
        //------------------------------------------------------------------
        if (soloidx >= 0) {     // is a solo coming up?
            if (inTime >= soloStart) {      // have we reached the solo time?
                inTime = soloStopTime(song,soloidx);    // yes: move past the solo
                soloidx += 1;
                if (soloidx >= song.solos.length) {
                    soloidx = -1;   // no more solos
                } else {
                    soloStart = soloStartTime(song,soloidx);   // next solo starts here
                }
            }
        }
    }
}

function mainscript() {
    buildLyricVid();
}

app.beginUndoGroup("Add Lyrics");
    mainscript();
app.endUndoGroup();
